[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino

upload_port = COM3
monitor_port = COM3
upload_speed = 57600
monitor_speed = 9600


lib_deps =
    teckel12/NewPing@^1.9.7
    bxparks/AceButton@^1.10.1
